<div class="slideshow-container">
    <?php
        foreach ($block->getPortfolioItem()['portfolioImages'] as $portfolioImage):?>
            <div class="mySlides fade">
                <img
                    src="<?= $block->getMediaUrl() . 'encentura/tmp/feature/' . $portfolioImage ?>"
                    style="width:100%">
            </div>
    <?php endforeach; ?>
    <!-- Nút điều khiển mũi tên-->
    <a class="prev" onclick="plusSlides(-1)">❮</a>
    <a class="next" onclick="plusSlides(1)">❯</a>
</div>
<br>

<div class="portfolio_content">
    <?= $block->getPortfolioItem()['portfolioContent'] ?>
</div>

<script>
    var slideIndex = 1;
    showSlides(slideIndex);

    function plusSlides(n) {
        showSlides(slideIndex += n);
    }

    function currentSliplusSlidesde(n) {
        showSlides(slideIndex = n);
    }

    function showSlides(n) {
        var i;
        var slides = document.getElementsByClassName("mySlides");
        if (n > slides.length) {
            slideIndex = 1
        }
        if (n < 1) {
            slideIndex = slides.length
        }
        for (i = 0; i < slides.length; i++) {
            slides[i].style.display = "none";
        }
        slides[slideIndex - 1].style.display = "block";
    }
</script>



